name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 12.x
      
      # Instalar dependencias
      - name: Install dependencies
        run: yarn
      
      # Executar Build  
      - name: Run Build
        run: yarn build
        
      - name: copy dist to digital ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "~/app/barber-back-end"
